### ISSUE TITLE
建议加备用网址

### ISSUE THREAD

**Issue by jcjrobert** [bingganhe123/60s-#1]
https://api.2xb.cn/zaob
这个也可以发60s作为备用
优客api有时候会崩
这个api有时候图片发送不全

**Comment by bingganhe123** [comment]
> https://api.2xb.cn/zaob 这个也可以发60s作为备用 优客api有时候会崩 这个api有时候图片发送不全

感谢，我这就去改一下

**Comment by bingganhe123** [comment]
> https://api.2xb.cn/zaob 这个也可以发60s作为备用 优客api有时候会崩 这个api有时候图片发送不全

已经更改上传，感谢您的帮助
