### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Winj1e** [bingganhe123/60s-#4]
![image](https://user-images.githubusercontent.com/105339518/168775082-7f9063b3-171b-4fec-ac06-3ecb07971a8c.png)
如图，请问这是哪里有问题啊？

**Comment by bingganhe123** [comment]
有可能是群号的时候输错了，或者逗号没有英文输入

**Comment by Winj1e** [comment]
确实是这样，打扰了

**Comment by Winj1e** [comment]
![image](https://user-images.githubusercontent.com/105339518/168789592-d1d94481-c2bd-4520-bda5-33705a1bbd9c.png)
现在他报错了，请问一下是哪里出了问题呢？

**Comment by Winj1e** [comment]
现在又可以了![3U( BK(%L67XQ8KK$JR}~KH](https://user-images.githubusercontent.com/105339518/168824942-e755ef7d-d53e-4f8c-9d56-117368652f72.png)
